<a href="https://colab.research.google.com/github/pavanthiriveedi7-rgb/Meachine_Learning_practice/blob/main/Multi_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

y = m1 * x1 + m2 * x2 + m3 * x3

where:
  
  y = dependent be variable

  x1 , x2 , x3 = independent be variable
  
  m1,m2,m3 = interupts

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [28]:
df = pd.read_csv("/content/hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [29]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [30]:
df.isnull()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        True                  False                       False      False
1        True                  False                       False      False
2       False                  False                       False      False
3       False                  False                       False      False
4       False                  False                       False      False
5       False                  False                       False      False
6       False                   True                       False      False
7       False                  False                       False      False

In [31]:
df.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [32]:
df['test_score(out of 10)'].median()

8.0

In [33]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].median())

In [34]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [35]:
df['experience'] = df['experience'].fillna('zero')

In [36]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  8 non-null      object 
 1   test_score(out of 10)       8 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes


In [42]:
reg = linear_model.LinearRegression()
!pip install word2number
from word2number import w2n
# Convert 'experience' column from word to number
df['experience'] = df['experience'].apply(w2n.word_to_num)
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [43]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [44]:
reg.intercept_

np.float64(17737.263464337688)

In [45]:
reg.predict([[4,8,8]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([61396.65211063])

In [46]:
# y = m1 * x1 + m2 * x2 + m3 * x3
2812.95487627 * 4 + 1845.70596798 * 8 + 2205.24017467 * 8 + 17737.263464337688

61396.65211061769

In [47]:
reg.predict([[5,10,10]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([72311.4992722])

In [48]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [49]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])