<a href="https://colab.research.google.com/github/pavanthiriveedi7-rgb/Meachine_Learning_practice/blob/main/save_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv('/content/homeprices.csv')

In [3]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
p = linear_model.LinearRegression()
p.fit(df[['area']],df['price'])

LinearRegression()

In [6]:
p.coef_

array([135.78767123])

In [7]:
p.intercept_

np.float64(180616.43835616432)

In [9]:
p.predict(np.array([[5000]]))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [12]:
p.predict([[5000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [13]:
import pickle

In [15]:
with open('model_pickle','wb') as f:
  pickle.dump(p,f)

In [16]:
with open('model_pickle','rb') as f:
  mp = pickle.load(f)

In [18]:
mp.predict([[5000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [22]:
import joblib

In [23]:
joblib.dump(p,'model_joblib')

['model_joblib']

In [24]:
mj = joblib.load('model_joblib')

In [25]:
mj.predict([[5000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [26]:
mj.coef_

array([135.78767123])

In [27]:
mj.intercept_

np.float64(180616.43835616432)

### 1. Efficiency with Large Data
The biggest reason to choose one over the other is NumPy.

Pickle treats a massive NumPy array as a standard Python object. This can lead to slow "copying" and high memory usage.

Joblib detects NumPy arrays and handles them using specialized "fast-path" code. Instead of loading everything into memory at once, it uses memory mapping (mmap), which makes reading large datasets much faster.

### 2. The Multi-File Quirk
When you save a complex object with Pickle, you get one single file. When you save a model with Joblib (especially older versions), it might create one main file and several sub-files (like .npy files) for each large array in your model. If you move your model to another folder, you have to remember to move all those files, not just the main one.

### 3. Security Warning
Important Note: Both Pickle and Joblib are not secure. Never "unpickle" a file you downloaded from an untrusted source. It is possible to craft a malicious file that executes arbitrary code on your machine the moment you try to load it.

### Which one should you use?
Use Pickle for small, standard Python objects (like a list of user settings or a dictionary of strings).

Use Joblib for saving and loading Scikit-learn models, large NumPy arrays, or anything involving heavy numerical data.